### ISSUE TITLE
When is our first meeting of next semester?

### ISSUE THREAD

**Issue by addisonamiri** [LUGatGT/slides#1]

**Comment by MiningMarsh** [comment]
It looks like it is going to be on the 7th.

**Comment by illegalprime** [comment]
YEAH ON THE 7th
(Marking as "WON'T FIX: FEATURE NOT BUG")

**Comment by richardscollin** [comment]
It will be on the 7th. However these slides will be for the presentation on the 14th. I will put together a presentation before Wednesday on duckduckgo and [duckduckhack](http://duckduckhack.com). Will send out an announcement soon.

**Comment by richardscollin** [comment]
Sorry guys. I just talked with Alyshia and there is no meeting this week. First meeting will be next week on Jan 14th.
